### ISSUE TITLE
Regarding iP

### ISSUE THREAD

**Issue by shreytheshreyas** [nus-cs2113-AY2021S1/forum#10]
Hi Prof,
In our Level-0 Greet implementation of the iP our we suppose to retain the initial logo "Duke" that was initially present or do we just remove the logo for now and just add in the code to greet the user?

**Comment by zhixiangteoh** [comment]
I believe you can keep it, change it, or remove it.

**Comment by felixhalim** [comment]
Please refer to #5

**Comment by okkhoy** [comment]
both @zhixiangteoh  and @felixhalim  are correct :-)

**Comment by shreytheshreyas** [comment]
oh ok thanks guys :)
