### ISSUE TITLE
CATcher Log-in Failure: [Error: Unauthorized user] 

### ISSUE THREAD

**Issue by t170815518** [nus-cs2113-AY2021S1/forum#100]
I cannot log-in using this Github account on CATcher 3.3.2 on Mac OS, because it said I am `Error: Unauthorized user`. 
![image](https://user-images.githubusercontent.com/42442406/96818555-43aaaf80-1454-11eb-9f4e-f51156555948.png)

What should I do?

Thank you for any kind of help

**Comment by hughjazzman** [comment]
You are part of https://github.com/nus-cs2113-AY2021S1 not CS2103.

**Comment by t170815518** [comment]
@hughjazzman  ahhhh, thanks for pointing out
