### ISSUE TITLE
Indentation settings on wrap lines

### ISSUE THREAD

**Issue by adinata15** [nus-cs2113-AY2021S1/forum#11]
Regarding the settings for the wrapped lines, do we include the indentation spaces into the 120 chars limit?
It is on this part of the website settings:

![image](https://user-images.githubusercontent.com/48993548/90884968-4f8ddd00-e3e3-11ea-94a5-679e06c720c8.JPG)

**Comment by hughjazzman** [comment]
I assume since the wrapped lines is about the layout to improve readability, it is so that the code is easily viewable on smaller widths. Then this means the spaces would be part of the limit.

**Comment by NeilBaner** [comment]
Agreed, I'm fairly sure indentation counts towards the limit. 

Don't ask me what happens if you have 30 levels of nested indentation though.

**Comment by okkhoy** [comment]
@adinata15 yes indentation spaces are counted. (@hughjazzman is correct)
@NeilBaner if you have 30 levels of indentation, I would say it is extremely horribly written code 😜

**Comment by adinata15** [comment]
Thank you!
