### ISSUE TITLE
SourceTree red exclamation mark beside Remote icon

### ISSUE THREAD

**Issue by HengFuYuen** [nus-cs2113-AY2021S1/forum#13]
Hi prof! Is it a problem if there is a red exclamation mark next to my remote icon on SourceTree (refer to picture below)? It seems to be able to successfully redirect me to the github page when I click on it although I have not tried to push any new commits yet.

![image](https://user-images.githubusercontent.com/60005925/90949168-bb6e5500-e478-11ea-87f7-968047b02150.png)
 
Thank you very much!

**Comment by okkhoy** [comment]
Another of your friend had the same issue; it doesn't seem to affect any functionality. 
Go ahead to use SourceTree as per normal. Things should work fine.

I have no clue what that is supposed to indicate. I looked around a bit on the internet, but haven't been able to find the exact cause.

**Comment by HengFuYuen** [comment]
Ok! Thank you very much prof!
