### ISSUE TITLE
[Week 3 Ex2] Using Accessors/Getters vs directly accessing member variables

### ISSUE THREAD

**Issue by NeilBaner** [nus-cs2113-AY2021S1/forum#14]
Hi Prof,

Week 3 Ex2 on repl.it requires us to calculate the area of a rectangle object, by multiplying its height and width together. Is it recommended to use the getter methods for the dimensions of the rectangle, or to just directly access the height and width variables? I noticed the model solution used the latter approach, but I used the getter methods myself. 

The comments in the skeleton code suggest using the setter for changing the dimensions rather than directly modifying the member variables, so I'm wondering why the model solution accessed the member variables directly rather than using the getters. 

Thank you, have a great day!

**Comment by okkhoy** [comment]
In general, it is better to make the attributes private and use accessor methods. 

However, for the model solution, let us say, we didn't follow what we preach 😜 🙈
