### ISSUE TITLE
[Week 3 Ex3] Instructions slightly unclear

### ISSUE THREAD

**Issue by NeilBaner** [nus-cs2113-AY2021S1/forum#15]
https://nus-cs2113-ay2021s1.github.io/website/schedule/week3/topics.html#key-exercise-pass-objects-to-move-method

The instructions for creating the move method specifies the following behaviour:

>* Returns null and does nothing if either p or r is null
>* Returns a new Point object that has attributes x and y that match those of r
>* Does not modify p
>* Updates r so that its attributes x and y match those of p

I think the instructions do not make clear whether the returned Point object should have attributes x and y matching those of r before the modification or after. 

The expected output seems to indicate that it is the former; that is, the method returns the previous/initial position of the rectangle as a Point. There's also little point (no pun intended) in directly returning one of the parameters. 

Perhaps the written instructions could be made slightly more explicit in mentioning this?

**Comment by okkhoy** [comment]
When you click on the hint you get this:
![image](https://user-images.githubusercontent.com/1023494/90974702-0d3dda80-e560-11ea-834b-5d40c55b2475.png)

Doe this answer your question?

**Comment by NeilBaner** [comment]
Ah, I didn't look at the hint. I figured it out when I saw the expected output. Thank you!
