### ISSUE TITLE
💡[repl.it] Replit Java version

### ISSUE THREAD

**Issue by NeilBaner** [nus-cs2113-AY2021S1/forum#16]
Note that repl.it uses Java version 1.8.0, aka Java 8, NOT Java 11 as we are using for class normally. This may or may not have implications for one of the exercises, due to differences in the String class (eg. Java 11 having some very convenient additions not present in Java 8...)

**Comment by okkhoy** [comment]
Good point; however repl.it provides us with Java 8 only (at least based on my checking), so we live with it.

**Comment by NeilBaner** [comment]
Since we no longer need Replit, I guess this issue can be closed.
