### ISSUE TITLE
IP Level-3 Question

### ISSUE THREAD

**Issue by matthewgani** [nus-cs2113-AY2021S1/forum#17]
Hi Prof, for IP level-3 (mark as done), do we have to account for the cases where the user inputs a task number(positive or negative) that does not exist or if the user simply inputs done with no number and print out an error message?

Thank you!

**Comment by zhixiangteoh** [comment]
I sure hope error-handling is not required considering we technically haven't gone over try-catch statements and other error-handling, but I am curious to know as well!

**Comment by okkhoy** [comment]
For Level-3, not necessary.
