### ISSUE TITLE
Repl.it Error: Note: Recompile with -Xlint:unchecked for details.

### ISSUE THREAD

**Issue by t170815518** [nus-cs2113-AY2021S1/forum#18]
I am attempting `Week 3 Ex9: filterEmails method`, using `java.util.ArrayList`; however, repl.it prompts the message in output like:
```
Note: Main.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint: unchecked for details.
[]
[]
[adam@example.com, john@example.com, some@]
[@bee.com]
```
where the first 2 lines make the output different from the expected and thus the solution cannot be accepted.
My full code:
```java
import java.util.ArrayList;
import java.util.Arrays;

public class Main {
    public static String[] filterEmails(String[] items){
        // TODO: add your code here
        ArrayList filteredList = new ArrayList();
        for (String email: items){
            if (email.contains("@")){
                filteredList.add(email);
            }
        }
        String[] result = new String[filteredList.size()];
        filteredList.toArray(result);
        return result;
    }

    public static void printItems(String[] items){
        // TODO: add your code here
        System.out.println(Arrays.toString(items));
    }

    public static void main(String[] args) {
        printItems(filterEmails(new String[]{}));
        printItems(filterEmails(new String[]{"abc"}));
        printItems(filterEmails(new String[]{"adam@example.com", "aab", "john@example.com", "some@"}));
        printItems(filterEmails(new String[]{"xyz", "@bee.com", "aab"}));
    }
} 
```
How can I solve the issue, especially the one that ` Recompile with -Xlint: unchecked for details.`? (I tried searching from StackOverflow but failed to understand the answers there. :( )

Any help will be appreciated. :)

**Comment by okkhoy** [comment]
Can you please tell which repl.it session you are in? The original one or the duplicated one?

**Comment by wangqinNick** [comment]
I think perhaps it is because you use the ArrayList, but you did not declare the generic. 
Since generic does not do type-check and  you did not declare either, it gave such warning.
Try  ArrayList  < String >  filteredList = new ArrayList <>();

**Comment by okkhoy** [comment]
Good catch @wangqinNick I didn't notice that earlier when I saw the post 🙈.

**Comment by t170815518** [comment]
> I think perhaps it is because you use the ArrayList, but you did not declare the generic.
> Since generic does not do type-check and you did not declare either, it gave such warning.
> Try ArrayList < String > filteredList = new ArrayList <>();

That works, thank you! It seems both warnings are caused because of it.
