### ISSUE TITLE
Glitter link broken

### ISSUE THREAD

**Issue by NeilBaner** [nus-cs2113-AY2021S1/forum#2]
Good day :)

I might be getting ahead of myself, but I was trying to access the class Gitter chat, and can't seem to do so. 
The first link on [this](https://nus-cs2113-ay2021s1.github.io/website/admin/tools.html) page, which appears to link to https://nus-cs2113-ay2021s1.github.io/website/admin/urt_gitter, leads me to a 404 page on GitHub, while the other link https://gitter.im/nus-cs2113-AY2021S1/community takes me to a 404 on the Gitter website. 

Is the chat just not up yet?

**Comment by okkhoy** [comment]
@NeilBaner  thanks! Gitter is not set up, yet. I will do so soon.

**Comment by NeilBaner** [comment]
Ah, thank you. I suspected I was being a bit eager. I'll check back later.

**Comment by okkhoy** [comment]
@NeilBaner  https://nus-cs2113-ay2021s1.github.io/website/admin/urt_gitter is a typo. I have fixed it now to point to the correct Gitter community (which is active now!)
