### ISSUE TITLE
Week 3 Tutorial Exercise - Coding Standard Violations

### ISSUE THREAD

**Issue by hughjazzman** [nus-cs2113-AY2021S1/forum#20]
```Java
import java.util.*;

public class Task {
    public static final String descriptionPrefix = "description: ";
    private String description;
    private boolean important;
    List<String> pastDescription = new ArrayList<>(); // a list of past descriptions

    public Task(String d) {
      this.description = d;
      if (!d.isEmpty())
          this.important = true;
    }

    public String getAsXML() { return "<task>"+description+"</task>"; }

    /**
     * Print the description as a string.
     */
    public void printingDescription(){ System.out.println(this); }

    @Override
    public String toString() { return descriptionPrefix + description; }
}
```
Other than the given ones regarding `descriptionPrefix`, `printingDescription()`, and `important`, these should be the other ones:

- `import java.util.*` should be `import java.util.ArrayList` to be explicit
- `pastDescription` should be `pastDescriptions` to indicate collection
- `this.description = d` can just be `description = d` to reduce noise
- `if` statement should be in wrapped in brackets 
- `getAsXML()` should be `getAsXml()` - lowercase

Did I miss anything?

**Comment by okkhoy** [comment]
You will collectively find out in the tutorial 😄
