### ISSUE TITLE
iP: Level-3

### ISSUE THREAD

**Issue by R-Ramana** [nus-cs2113-AY2021S1/forum#21]
For Level-3 of the iP, can we assume that the input from the user will always be done < int > and no other variations like < int > done/I have done < int >?

**Comment by hughjazzman** [comment]
I would assume all the input we get is completely ideal, and that we will learn about catching errors in future weeks.

**Comment by felixhalim** [comment]
Error-handling is not necessary for Level-3. Based on #17

**Comment by okkhoy** [comment]
@hughjazzman and @felixhalim are correct. for Level-3 it is not necessary to do error handling

**Comment by R-Ramana** [comment]
Thanks all
