### ISSUE TITLE
Automated Text UI Testing

### ISSUE THREAD

**Issue by hughjazzman** [nus-cs2113-AY2021S1/forum#22]
OS: Windows 10
Increment: [`A-TextUiTesting`](https://nus-cs2113-ay2021s1.github.io/website/schedule/week4/project.html#a-textuitesting)
File: `runtest.bat`

While working on the increment, I find an issue when using file compare (`FC`) for the special characters `✓` and `✘`. In the output file `ACTUAL.TXT`, the corresponding characters seem to get converted to `?` (question mark), and the follow lines will be shown in the diff:
```
Comparing files ACTUAL.TXT and EXPECTED.TXT
***** ACTUAL.TXT
 Got it. I've added this task:
  [D][?] do homework (by: no idea)
 Now you have 8 tasks in the list.
***** EXPECTED.TXT
 Got it. I've added this task:
  [D][Γ£ÿ] do homework (by: no idea)
 Now you have 8 tasks in the list.
*****

***** ACTUAL.TXT
 Nice! I've marked this task as done:
 [T][?] read book
------------------------------------------------------------
***** EXPECTED.TXT
 Nice! I've marked this task as done:
 [T][Γ£ô] read book
------------------------------------------------------------
*****
```
To fix it, I basically had to change the the expected character to be a `?` in `EXPECTED.TXT` and it will give me that no differences were encountered. However, this would mean that the test cannot check for `✓` and `✘` characters being different.

I guess that the error probably comes from the special characters being unicode characters which is an issue if `FC` isn't expecting it. From the [docs](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fc), there is an option for unicode, but it will be on the whole file and not just a single character.

I also note that in [Updating test as the program evolves](https://se-education.org/guides/tutorials/textUiTesting.html#updating-tests-as-the-program-evolves), "we accept that the actual behavior should be the new expected behavior".

Is there any way for the test to check for those characters, or should I just stick with the question marks?

**Comment by wangqinNick** [comment]
There is a line in runtest.sh doing "# run the program, feed commands from input.txt file and redirect the output to the ACTUAL.TXT"
Change it to:
java -Dfile.encoding=UTF-8 -classpath ../bin sample.Main < input.txt > ACTUAL.TXT
don't forget to change the class name to yours
(I am using a Mac and not sure if this works or not. )

**Comment by hughjazzman** [comment]
Nice! It works, thanks @wangqinNick.

**Comment by kaijiel24** [comment]
I faced the same issue and after implementing @wangqinNick solution, the terminal will still show ```Γ£ÿ``` and ```Γ£ô``` instead of ```✘``` and ```✓``` when I have yet to change the ```EXPECTED.txt``` to match ```ACTUAL.txt```. But when I open ```ACTUAL.txt``` it shows ```✘``` and ```✓``` correctly. 
After I changed ```EXPECTED.txt``` to match ```ACTUAL.txt```, no differences will be detected when I run runtest.bat so I believe it is the terminal that is not able to show the correct symbol rather than java.
```
Comparing files ACTUAL.TXT and EXPECTED.TXT
FC: no differences encountered
```

**Comment by hughjazzman** [comment]
@kaijiel24 Yep, since they are special characters you would need to change the console code page as well as the font to print them. Of the fonts available in my `cmd`, only MS Gothic, NSimSun, SimSun-ExtB could display them.
```
chcp 65001
```

Sources:
https://ss64.com/nt/chcp.html
https://github.com/rrrene/credo/issues/422
