### ISSUE TITLE
No Invitation to nus-cs2113-AY2021S1

### ISSUE THREAD

**Issue by brandonywl** [nus-cs2113-AY2021S1/forum#25]
Hi.

I did not receive any invite to the organization and tried to follow the link in the admin info but did not work.

I just made the pull request a couple of hours earlier. Is that a factor?

**Comment by felixhalim** [comment]
Same case here

**Comment by okkhoy** [comment]
Will be sent later in the week.

**Comment by felixhalim** [comment]
Noted. Thanks prof.

**Comment by NeilBaner** [comment]
I appear to have received the invite a few hours ago.

**Comment by okkhoy** [comment]
yup. it was sent last night.
