### ISSUE TITLE
Policy on use of "this" keyword

### ISSUE THREAD

**Issue by NeilBaner** [nus-cs2113-AY2021S1/forum#27]
Can I clarify when we are expected to use the "this" keyword to access member variables in a class? Personally, I prefer to use "this" at all times to be explicit, but I seem to remember being told (either in lecture or in tutorial, can't seem to recall which) not to use it when not required to cut down on clutter. I couldn't find anything on this in the Java coding standard guide. The notes on the website on the use of the "this" keyword don't cover this either. 

I just wanted to confirm if I should always use it or not?

Thank you!

**Comment by hughjazzman** [comment]
It’s here: https://se-education.org/guides/conventions/java/index.html#variables

>  **Avoid unnecessary use of `this` with fields.**

> Use the `this` keyword only when a field is shadowed by a method or constructor parameter.

**Comment by NeilBaner** [comment]
Ah, thank you @hughjazzman don't know how I missed that.
