### ISSUE TITLE
Commit date and time being messed up due to rebase

### ISSUE THREAD

**Issue by limgl1998** [nus-cs2113-AY2021S1/forum#28]
For some reasons, I had to rebase my commit history to merge 2 different branches. As a result, the timings for my commits became very recent (ie all the commit timings became that of the time where I did my rebase). Will I be penalised because of my commit timings as they are past the deadlines?

**Comment by okkhoy** [comment]
It will be marked late for the week but if you do the rest of the things on time, it should not affect you much.
