### ISSUE TITLE
Automated Text-UI Testing Issue : Cannot find file

### ISSUE THREAD

**Issue by adinata15** [nus-cs2113-AY2021S1/forum#29]
I am still a bit confused about automated testing. After following the guide on the cs2113 website and changing the path, I still get the error:
```
Error: Could not find or load main class Duke
Caused by: java.lang.NoClassDefFoundError: main/java/Duke (wrong name: Duke)
```
![image](https://user-images.githubusercontent.com/48993548/91651424-13333e80-eabf-11ea-807b-10f801ebb4f8.png)
These are my java and javac command lines:
```
javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java
java -Dfile.encoding=UTF-8 -classpath ..\bin\main\java Duke < input.txt > ACTUAL.TXT
```
Does anyone know how to solve this error? Thank you!

**Comment by zhixiangteoh** [comment]
Because you compiled the files into `<root>/bin/`, your java command should be

`java -Dfile.encoding=UTF-8 -classpath ..\bin Duke < input.txt > ACTUAL.TXT` ?

**Comment by wangqinNick** [comment]
This is perhaps you have changed you main class name, or moved it to another package. 
You can try to change this line.
For example, if you have moved it to another package, you should also compile it with your class name with the package's name
eg. "sample.Main".
java -Dfile.encoding=UTF-8 -classpath ../bin sample.Main < input.txt > ACTUAL.TXT

**Comment by AndreWongZH** [comment]
![image](https://user-images.githubusercontent.com/21986187/91651800-a53d4600-eac3-11ea-809f-b56cf0302e4b.png)

Maybe you did not initialize a value and called it?

**Comment by okkhoy** [comment]
@adinata15 please try the suggestion given by @zhixiangteoh first and let us know if you can get it to work.

**Comment by adinata15** [comment]
@zhixiangteoh  When ```java -Dfile.encoding=UTF-8 -classpath ..\bin Duke < input.txt > ACTUAL.TXT``` is used, it still gives the same error.
@wangqinNick Regarding file location, I do not create another package nor more the file from src/main/java. 
@AndreWongZH For the uninitialised value, I declared some variable without assigning a value for them at first (only assign when user input data) but everything works fine when I tried running it on the console.

**Comment by zhixiangteoh** [comment]
> @zhixiangteoh When `java -Dfile.encoding=UTF-8 -classpath ..\bin Duke < input.txt > ACTUAL.TXT` is used, it still gives the same error.
> @wangqinNick Regarding file location, I do not create another package nor more the file from src/main/java.
> @AndreWongZH For the uninitialised value, I declared some variable without assigning a value for them at first (only assign when user input data) but everything works fine when I tried running it on the console.

Your main class and file are still "Duke" and "Duke.java" respectively?

**Comment by adinata15** [comment]
> > @zhixiangteoh When `java -Dfile.encoding=UTF-8 -classpath ..\bin Duke < input.txt > ACTUAL.TXT` is used, it still gives the same error.
> > @wangqinNick Regarding file location, I do not create another package nor more the file from src/main/java.
> > @AndreWongZH For the uninitialised value, I declared some variable without assigning a value for them at first (only assign when user input data) but everything works fine when I tried running it on the console.
> 
> Your main class and file are still "Duke" and "Duke.java" respectively?

I am not sure where to find the file Duke.java but my main class is still Duke. This is the screenshot of the directory:
![image](https://user-images.githubusercontent.com/48993548/91656076-3f16ea00-eae8-11ea-9478-c6a95cb3cec1.png)

**Comment by zhixiangteoh** [comment]
> > > @zhixiangteoh When `java -Dfile.encoding=UTF-8 -classpath ..\bin Duke < input.txt > ACTUAL.TXT` is used, it still gives the same error.
> > > @wangqinNick Regarding file location, I do not create another package nor more the file from src/main/java.
> > > @AndreWongZH For the uninitialised value, I declared some variable without assigning a value for them at first (only assign when user input data) but everything works fine when I tried running it on the console.
> > 
> > 
> > Your main class and file are still "Duke" and "Duke.java" respectively?
> 
> I am not sure where to find the file Duke.java but my main class is still Duke. This is the screenshot of the directory:
> ![image](https://user-images.githubusercontent.com/48993548/91656076-3f16ea00-eae8-11ea-9478-c6a95cb3cec1.png)

Hey, i think perhaps this will work:

`java -Dfile.encoding=UTF-8 -classpath ..\bin main\java\Duke < input.txt > ACTUAL.TXT`

It seems that because your compilation destination is <root>\bin but the package main.java was compiled and not the files, the classpath is ..\bin but you need to execute the `<package>.<subpackage>.<main class>`.

See also: https://stackoverflow.com/questions/7509295/noclassdeffounderror-wrong-name/13697239

If this still doesn't work, try changing your javac command in runtest.bat to:

`javac  -verbose -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java`

to see what files or packages are being loaded.

**Comment by adinata15** [comment]
> > > > @zhixiangteoh When `java -Dfile.encoding=UTF-8 -classpath ..\bin Duke < input.txt > ACTUAL.TXT` is used, it still gives the same error.
> > > > @wangqinNick Regarding file location, I do not create another package nor more the file from src/main/java.
> > > > @AndreWongZH For the uninitialised value, I declared some variable without assigning a value for them at first (only assign when user input data) but everything works fine when I tried running it on the console.
> > > 
> > > 
> > > Your main class and file are still "Duke" and "Duke.java" respectively?
> > 
> > 
> > I am not sure where to find the file Duke.java but my main class is still Duke. This is the screenshot of the directory:
> > ![image](https://user-images.githubusercontent.com/48993548/91656076-3f16ea00-eae8-11ea-9478-c6a95cb3cec1.png)
> 
> Hey, i think perhaps this will work:
> 
> `java -Dfile.encoding=UTF-8 -classpath ..\bin main\java\Duke < input.txt > ACTUAL.TXT`
> 
> It seems that because your compilation destination is \bin but the package main.java was compiled and not the files, the classpath is ..\bin but you need to execute the `<package>.<subpackage>.<main class>`.
> 
> See also: https://stackoverflow.com/questions/7509295/noclassdeffounderror-wrong-name/13697239
> 
> If this still doesn't work, try changing your javac command in runtest.bat to:
> 
> `javac -verbose -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java`
> 
> to see what files or packages are being loaded.

I try changing it to:
```
java -Dfile.encoding=UTF-8 -classpath ..\bin main\java\Duke < input.txt > ACTUAL.TXT
```
The same error still comes out. However, when I change it to:
```
java -Dfile.encoding=UTF-8 -classpath ../bin main/java/Duke < input.txt > ACTUAL.TXT
```
It works :D. I then try to change all backslash to slash in the runtime.bat file and it also works. I am not really sure why this works, but could this lead to a problem in the future?

**Comment by hughjazzman** [comment]
@adinata15 What's your OS? The forward/backslash seems like something to do with using the right file on the right OS.

**Comment by adinata15** [comment]
> @adinata15 What's your OS? The forward/backslash seems like something to do with using the right file on the right OS.

My OS is Windows 10.
![image](https://user-images.githubusercontent.com/48993548/91663554-317b5780-eb1c-11ea-94f8-405953cc9bc1.png)
The Windows 10 version might be the cause, is it?

**Comment by hughjazzman** [comment]
@adinata15 Hmm then maybe not. Looking at your package structure, because you packaged Duke in `main.java` I believe these should work:

```bash
javac -cp ..\src -Xlint:none -d ..\bin ..\src\main\java\Duke.java
java -Dfile.encoding=UTF-8 -classpath ..\bin main.java.Duke < input.txt > ACTUAL.TXT
```

**Comment by riazaham** [comment]
![image](https://user-images.githubusercontent.com/60385689/92317639-d1157a00-f035-11ea-8638-a9b9cbaf228b.png)

I tried runtest but the ACTUAL.txt file could not be found. Anyone has any idea...?

**Comment by wangqinNick** [comment]
> ![image](https://user-images.githubusercontent.com/60385689/92317639-d1157a00-f035-11ea-8638-a9b9cbaf228b.png)
> 
> I tried runtest but the ACTUAL.txt file could not be found. Anyone has any idea...?

I have no clear thought. But I am interested in your structure :/
You project content root is week4circus, instead of circus as normal. Did you import the project or you just open it? Could you click File -> Project Structure ->modules and screen shot your modules?

**Comment by riazaham** [comment]
> > ![image](https://user-images.githubusercontent.com/60385689/92317639-d1157a00-f035-11ea-8638-a9b9cbaf228b.png)
> > I tried runtest but the ACTUAL.txt file could not be found. Anyone has any idea...?
> 
> I have no clear thought. But I am interested in your structure :/
> You project content root is week4circus, instead of circus as normal. Did you import the project or you just open it? Could you click File -> Project Structure ->modules and screen shot your modules?

![image](https://user-images.githubusercontent.com/60385689/92318550-661d7080-f040-11ea-8a50-b3bddd2a533c.png)

This is my project structure.
The "week4circus" is a folder created by me and I cloned the github repo into it

**Comment by okkhoy** [comment]
The ACTUAL file gets created on successfully running the `runtest.bat` file.
Were you able to run the `runtest.bat`?

**Comment by wangqinNick** [comment]
> > > ![image](https://user-images.githubusercontent.com/60385689/92317639-d1157a00-f035-11ea-8638-a9b9cbaf228b.png)
> > > I tried runtest but the ACTUAL.txt file could not be found. Anyone has any idea...?
> > 
> > 
> > I have no clear thought. But I am interested in your structure :/
> > You project content root is week4circus, instead of circus as normal. Did you import the project or you just open it? Could you click File -> Project Structure ->modules and screen shot your modules?
> 
> ![image](https://user-images.githubusercontent.com/60385689/92318550-661d7080-f040-11ea-8a50-b3bddd2a533c.png)
> 
> This is my project structure.
> The "week4circus" is a folder created by me and I cloned the github repo into it

Maybe you can try this: whenever you have ..\bin, you change it to ..\circus\bin
But in case it won't not work, you either "git reset" to reset it later, or save a copy of it beforehand.

**Comment by riazaham** [comment]
> The ACTUAL file gets created on successfully running the `runtest.bat` file.
> Were you able to run the `runtest.bat`?

Oh wow it works now.... :/ idk what changed but it works now! Thanks for the help
