### ISSUE TITLE
Automated runtest issues: cannot find symbol

### ISSUE THREAD

**Issue by yuxinwu99** [nus-cs2113-AY2021S1/forum#30]
I am getting this when trying out the runtest.bat for some reason. List is a custom class I declared. I have not changed my runtest.bat file at all.
![image](https://user-images.githubusercontent.com/60455558/91651518-432f1180-eac0-11ea-9d1c-4bbfc7616346.png)

**Comment by wangqinNick** [comment]
You need to declare and compile all the classes you have, not only the main class.
Like this:
if ! javac -cp ../src -Xlint:none -d ../bin ../src/main/java/sample.Main.java ../src/main/java/commands/add/*.java ../src/main/java/commands/*.java ../src/main/java/common/*.java ../src/main/java/data/exceptions/*.java ../src/main/java/data/task/*.java ../src/main/java/data/*.java ../src/main/java/parser/*.java ../src/main/java/storage/*.java ../src/main/java/ui/*.java

**Comment by wangqinNick** [comment]
Or you could run the test-ui by a jar file, which is more convenient when you have complicated structures such as multiple classes and packages.

**Comment by yuxinwu99** [comment]
Thank you so much! It works now.

**Comment by zhixiangteoh** [comment]
Just change this line in runtest.bat: `javac  -cp ..\src -Xlint:none -d ..\bin ..\src\main\java\Duke.java`

to 

`javac  -cp ..\src -Xlint:none -d ..\bin ..\src\main\java\*.java`, similar to in runtest.sh
