### ISSUE TITLE
Tick and Cross characters not appearing when doing text ui testing 

### ISSUE THREAD

**Issue by prachi2023** [nus-cs2113-AY2021S1/forum#31]
When I run the code on IntelliJ, the characters for the ticks and the cross appear. However, when I run the code using the command line, they appear as question marks. How to fix this issue? 

![IntelliJOutput](https://user-images.githubusercontent.com/60388723/91830275-28ea6480-ec75-11ea-85c9-806ffc07eb3b.PNG)
![commandLineOutput](https://user-images.githubusercontent.com/60388723/91830282-2982fb00-ec75-11ea-9532-2a5d8d7ff587.PNG)

**Comment by hughjazzman** [comment]
Answered in #22

**Comment by felixhalim** [comment]
To prevent repeated question regarding this, it would be better if the solution is added to the documentation. @okkhoy

**Comment by prachi2023** [comment]
Sorry I might have missed that. Thanks guys

**Comment by okkhoy** [comment]
Noted @felixhalim . Will add it for the future iteration. Now you all know what it is.
