### ISSUE TITLE
Automated Text-UI Testing Issue : Cannot find file and symbol

### ISSUE THREAD

**Issue by gmit22** [nus-cs2113-AY2021S1/forum#33]
I am not able to get the automated testing to work. It keeps on giving the error ACTUAL.txt not found and cannot find class that have been incorporated in the main class, resulting in a build failure.

**Comment by Colin386** [comment]
Hi there!
How does your file structure look like in the project?
![image](https://user-images.githubusercontent.com/60383990/91886910-9c639480-ecbc-11ea-8b07-f4480383a7aa.png)
If yours looks like this where you have a main.java folder with all the classes inside it, you may need to change the runtest.bat file:

instead of writing:
`java -classpath ..\bin Duke < input.txt > ACTUAL.TXT`
you will need to write:
`java -classpath ..\bin main.java.Duke < input.txt > ACTUAL.TXT`
Im not sure if this will help, but it did help me resolve the issue of missing classes. Do let me know how it goes

**Comment by okkhoy** [comment]
@gmit22 In addition to @Colin386 's question/suggestion above, if you have multiple classes, you need to compile all of them, not just the main.
See: https://se-education.org/guides/tutorials/textUiTesting.html 
The skeleton codebase for IP compiles only Duke.java (as that is the only file you have when you clone the repo).

**Comment by HengFuYuen** [comment]
I also had the same problem of a build failure and the terminal being unable to find the classes that I have used in Duke. However, I was testing things out and either of these two compile lines seems to make it work:
javac  -cp ..\src -Xlint:none -d ..\bin ..\src\main\java\Task.java
javac  -cp ..\src -Xlint:none -d ..\bin ..\src\main\java\*.java
However, I am not sure if this is correct.

**Comment by okkhoy** [comment]
@HengFuYuen using: `javac -cp ..\src -Xlint:none -d ..\bin ..\src\main\java\*.java` you are telling the compiler to compile all the `.java` in the `src\main\java\` directory. So that seems to be the correct one.

**Comment by HengFuYuen** [comment]
I see! Thanks for the clarification prof!

**Comment by gmit22** [comment]
@Colin386  
Hi, 
Yes that is my project structure, however, when I run the java -classpath ..\bin main.java.Duke < input.txt > ACTUAL.TXT, it gives me the error "Error: Could not find or load main class main.java.Duke". 
Even though an ACTUAL.txt is created, it does not get updated based on the inputs given.

<img width="228" alt="Capture" src="https://user-images.githubusercontent.com/59180102/91990284-2c521e80-ed4f-11ea-9b22-3f5deffd00d5.PNG">

**Comment by gmit22** [comment]
@HengFuYuen @okkhoy 
Yes this command worked to compile all the classes in the folder.

**Comment by wangqinNick** [comment]
> @Colin386
> Hi,
> Yes that is my project structure, however, when I run the java -classpath ..\bin main.java.Duke < input.txt > ACTUAL.TXT, it gives me the error "Error: Could not find or load main class main.java.Duke".
> Even though an ACTUAL.txt is created, it does not get updated based on the inputs given.
> 
> <img alt="Capture" width="228" src="https://user-images.githubusercontent.com/59180102/91990284-2c521e80-ed4f-11ea-9b22-3f5deffd00d5.PNG">

This is because your project structure. Your source file is "java" folder (the blue one in the picture) instead of src folder

<img width="240" alt="Screenshot 2020-09-03 at 4 41 34 PM" src="https://user-images.githubusercontent.com/50083580/92092174-56194d00-ee04-11ea-9613-f0ef9bd1d84e.png">

**Comment by wangqinNick** [comment]
You should either change the project structure or change the command in runtest.bat according to your current structure. 
To change the structure, you goto File->Project Structure-> source

Or perhaps try this, if you do not want to change your current structure.
java -classpath ..\bin Duke < input.txt > ACTUAL.TXT

**Comment by gmit22** [comment]
Yes I tried this, it works. Understood the problem, thanks
