### ISSUE TITLE
Questions regarding DukeException

### ISSUE THREAD

**Issue by wangqinNick** [nus-cs2113-AY2021S1/forum#34]
I want to ask the DukeException class should inherit whether the Exception class or the RuntimeException class.
The example in the textbook, uses the Exception class as the father class, but I find in the project, it is more convenient to use runtimeException as the father class.

**Comment by okkhoy** [comment]
It should inherit the `Exception` class. (`RuntimeException` is a subclass of Exception)
See: https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html

**Comment by wangqinNick** [comment]
> It should inherit the `Exception` class. (`RuntimeException` is a subclass of Exception)
> See: https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html

Thanks, I understand difference about checked and unchecked exceptions now.
