### ISSUE TITLE
Using * wildcard for imports

### ISSUE THREAD

**Issue by NeilBaner** [nus-cs2113-AY2021S1/forum#36]
Is it ever acceptable to use the * wildcard in an import statement? For example, I have a package called "task" with some different classes, all of which are accessed by my main Duke class in another package. Is it necessary to import every single class separately, or may I use, say, `import com.neilbaner.duke.task.*` ?

Thank you!

**Comment by zhixiangteoh** [comment]
I personally feel using explicit imports is still better; on top of the stated benefits, I feel it is also more flexible in that it allows you to more clearly and easily remove particular import statements in the event you reorganize your packages and/or the code in the class to which you are importing the packages/classes to.

**Comment by hughjazzman** [comment]
It's in the Coding Standard: https://se-education.org/guides/conventions/java/basic.html#package-and-import-statements

> Imported classes should always be listed explicitly.

**Comment by okkhoy** [comment]
@NeilBaner  No! not as per our coding standards

**Comment by NeilBaner** [comment]
Sorry for the late response. Understood. Thank you.

**Comment by NeilBaner** [comment]
Interesting update: If I use IntelliJ to automatically import each class (i.e. delete my import com.neilbaner.duke.exceptions.* and then Alt-Enter on each exception manually), then by the time I import every single exception (eg. import com.neilbaner.duke.exceptions.TaskIndexOutOfBoundsException, com.neilbaner.duke.exceptions.UnknownCommandException etc. etc, IntelliJ decides that it should combine them all back into com.neilbaner.duke.exceptions.*. This does throw a bit of a spanner in the works.

**Comment by hughjazzman** [comment]
Follow this: https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcard-imports
