### ISSUE TITLE
branch-Level-5 not detected in dashboard

### ISSUE THREAD

**Issue by ninggggx99** [nus-cs2113-AY2021S1/forum#39]
Hi, I have pushed the branch-Level-5 but it is not detected by the iP dashboard. May I know if there's anything I merged wrong?

![image](https://user-images.githubusercontent.com/20852776/92601861-e7466300-f2df-11ea-9632-948cc64082ab.png)

**Comment by iamchenjiajun** [comment]
I believe the dashboard is only updated once a week.

**Comment by ninggggx99** [comment]
> I believe the dashboard is only updated once a week.

I don't think so. The dashboard detected my Level-5 tag but not the branch

**Comment by Reinbowl** [comment]
I believe when creating branch-A-Packages later on, it might have messed up the branches as it shows the package branching from the level 5 branch and not from master.

**Comment by scjx123** [comment]
I think the script runs once a day, and its probably a good idea to try having your final merge as branch-Level-5.

**Comment by ninggggx99** [comment]
> I think the script runs once a day, and its probably a good idea to try having your final merge as branch-Level-5.

but its pushed to github already how do I leave the the final merge as branch-Level-5?

**Comment by scjx123** [comment]
> > I think the script runs once a day, and its probably a good idea to try having your final merge as branch-Level-5.
> 
> but its pushed to github already how do I leave the the final merge as branch-Level-5?

im not entirely sure if im right, but you can either create another branch and called it that, followed by a merge, or do a git reset back to your previous commit, and merge again.

**Comment by zhixiangteoh** [comment]
so your branch-A-Packages is found but not branch-Level-5? Might it be due to a small typo in the uppercase 'L', given that the name technically should be `branch-level-5`? Don't know if they accounted for typos like this.

Edit: It seems your `branch-A-Packages` is a branch from `branch-Level-5`, when it should be a branch from `master`?

**Comment by ninggggx99** [comment]
> so your branch-A-Packages is found but not branch-Level-5? Might it be due to a small typo in the uppercase 'L', given that the name technically should be `branch-level-5`? Don't know if they accounted for typos like this

branch-A-Packages is not checked on the dashboard. um its an upper case 'L' and my friends did with upper case 'L' worked but mine didn't

**Comment by zhixiangteoh** [comment]
> > so your branch-A-Packages is found but not branch-Level-5? Might it be due to a small typo in the uppercase 'L', given that the name technically should be `branch-level-5`? Don't know if they accounted for typos like this
> 
> branch-A-Packages is not even detected. um its an upper case 'L' and my friends did with upper case 'L' worked but mine didn't

from your commit history it seems you created the `branch-A-Packages` branch from `branch-Level-5`, but i think we are supposed to merge `branch-Level-5` into `master`, `git checkout master`, then `git branch branch-A-Packages` or `git checkout -b branch-A-Packages` from `master`.

**Comment by okkhoy** [comment]
I suspect you pushed the `branch-level-5` after the evaluation was done.  Please wait until the next run and update here if it is still missing. 
If all is well, please close the issue after you see the update.
