### ISSUE TITLE
Exercises in the Topics

### ISSUE THREAD

**Issue by MuhammadHoze** [nus-cs2113-AY2021S1/forum#4]
Hi prof, just wanted to check if the Exercises in the Topics are mandatory to do?

**Comment by okkhoy** [comment]
If you are talking about the ones on Repl.it, those are counted towards participation marks.
In your own interest, you should try to do them.
If it is not the ones on Repl.it, please specify.

**Comment by MuhammadHoze** [comment]
Yes besides the one on repl.it. 

 Exercises (For Example)

 SE vs Civil Engineering

 Software vs Bridges

 Coding as a manufacturing activity

 List pros and cons of SE

 Which one of these is not included in Brook’s list of ‘Woes of the Craft’?

Do these exercises also contribute to the participation marks?

**Comment by okkhoy** [comment]
No. Those exercises are not counted for any marks.
They are there just to help you review the relevant content.

**Comment by MuhammadHoze** [comment]
Alright thanks
