### ISSUE TITLE
[iP] Progress very out of date on the Code Dashboard

### ISSUE THREAD

**Issue by NeilBaner** [nus-cs2113-AY2021S1/forum#40]
Hi Prof and everyone,

I was looking through the RepoSense dashboard with all of our iPs, and I noticed that my iP is quite behind (the last commit was on 4th September). However, I have made more commits to my iP since then (including on the same day) but those don't seem to be picked up by RepoSense. I noticed others' commits as new as today are being picked up; is there something I'm doing wrong? Have I perhaps messed up a branch or something?

Thank you!

EDIT: Links for reference: [RepoSense for my iP](https://nus-cs2113-ay2021s1.github.io/ip-dashboard/#sort=totalCommits%20dsc&groupSelect=groupByAuthors&search=neilbaner&sortWithin=title&since=2020-08-14&timeframe=commit&mergegroup=&breakdown=false&tabOpen=true&tabType=zoom&zA=neilbaner&zR=neilbaner%2Fip%5Bmaster%5D&zACS=88.38133547868061&zS=2020-08-14&zFS=&zU=2020-09-10&zMG=false&zFTF=commit&zFGS=groupByAuthors), [GitHub for my iP](https://github.com/NeilBaner/ip/commits/master)

**Comment by wangqinNick** [comment]
The responseSense does not detect branch unless it has been merged to master and pushed to the remote. You just merge your level-five one hour ago and I think you can check the progress tomorrow. 

And similar for the tags, it might be that your tag for the levels does not point to commits in the main branch. Try checking if all the commits of the relevant tags can be found on your main branch. Tag the merging commits, instead of the branch commit.

**Comment by okkhoy** [comment]
Please also check the `git config user.name` on your machine.
If it doesn't match the one in the config : https://github.com/nus-cs2113-AY2021S1/ip-dashboard/blob/master/configs/author-config.csv
Make a PR to update the name in the last column (you need to separate out the names using semi colon).
Once that is merged, commits made using various names will be picked up.

**Comment by NeilBaner** [comment]
@wangqinNick Ahhh I think I see the problem then. Thank you. I also just double checked that all my tags were pushed because some of my tags this morning were only on my local repo :/ I was just very confused since no one else seemed to have this issue; perhaps they already merged their branches. 

@okkhoy The user.name seems to be fine. I'll wait for the reposense to update tomorrow. 

Thank you to everyone :)

**Comment by NeilBaner** [comment]
Update: All is well, the latest changes have been picked up.
