### ISSUE TITLE
branch-Level-5 not detected in dashboard

### ISSUE THREAD

**Issue by AmeliaTYR** [nus-cs2113-AY2021S1/forum#41]
Hi sorry I pushed branch-Level-5 two days ago (8sep) and it says the ip progress dashboard updated yesterday (9sep) but it still says it doesn't detect the branch-Level-5.  

![image](https://user-images.githubusercontent.com/53657436/92683529-b3ae1c00-f365-11ea-9b4d-7fdcf71ac6f1.png)
![image](https://user-images.githubusercontent.com/53657436/92683682-1bfcfd80-f366-11ea-850b-a6e6fe4a1118.png)

did I do something wrongly?

**Comment by okkhoy** [comment]
looks like you merged branch-level-5 to some other branch and not master?
notice that your master is behind the branch-level-5

**Comment by AmeliaTYR** [comment]
I merged the branch that it was merged to to the master is that ok?
![image](https://user-images.githubusercontent.com/53657436/92706420-119f2b80-f387-11ea-91f3-e2c1ffb424f7.png)
Or how do I undo the merging mess I made?

**Comment by ChanJianHao** [comment]
Hello, I believe you could try to revert the merge. Check [this](https://community.atlassian.com/t5/Sourcetree-questions/How-do-I-revert-abort-a-merge-using-source-tree/qaq-p/350099) out for more information.

**Comment by AmeliaTYR** [comment]
I reverted it to branch-Level-5 and then merged it to master so now it's like this:

![image](https://user-images.githubusercontent.com/53657436/92716900-043b6e80-f392-11ea-8f05-cbed905ed039.png)

master now has the latest version of the code 

is this acceptable? (also do i need to undo all of the other merge stuff I did or can I just leave it? I'm afraid I might accidentally delete something important?)

**Comment by okkhoy** [comment]
This looks good to me. Please monitor the dashboard, if it is still not fixed by tomorrow noon, let me know. I will check what is happening.

**Comment by AmeliaTYR** [comment]
Thank you @okkhoy and @ChanJianHao for your help!
