### ISSUE TITLE
[General] Forking vs Branching for group projects

### ISSUE THREAD

**Issue by NeilBaner** [nus-cs2113-AY2021S1/forum#44]
As NUS SoC students, we all have to do many group projects, most of which involve collaborating on code. I've used GitHub in the past for this, but mostly in the very simple "everyone just commits to master" style. Of course, with CS2113T, we're all now more familiar with advanced git and revision control strategies. 

Prof, can I ask, in your opinion, for the type of small group project that we often undertake, what's the best approach of these:

- Creating a GitHub Organisation for the project and creating a repository under the organisation that everyone contributes to via forks and PRs. 
- One member making a repository on their account and everyone making a fork and submitting PRs. 
- One member making a repository on their account and everyone making a separate branch and submitting PRs. 
- One member making a repository on their account and everyone committing to a separate "development" branch, and then submitting PRs to master.
- Committing directly to master. 

While PRs are very good for organising code, I think they can be a bit of a hassle for smaller projects where speed is more important than code quality (as long as there are no bugs, which should be tested before committing). I wonder if Prof has any advice on choosing an approach? Or maybe any of my classmates have any ideas/stories/suggestions? 

Thank you all in advance, have a lovely weekend!

**Comment by okkhoy** [comment]
Within the scope of this module, you are required to create the organization for your project.
Each of you then fork from the organization repository, contribute, and PR to the org repo.
(at least for the first few weeks in the project, we track this and use it for grading).

In general, PR workflow, though cumbersome, is a good thing to follow as it helps manage the project better and maintain a cleaner production repo.
However, depending on the team dymanics and proficiency of the team members, you can follow a workflow that best suits the team.

In the professional world, the companies have their own workflows (mostly involving PRs) and you need to follow them.

**Comment by NeilBaner** [comment]
Thank you for the helpful insight. When you say PR workflow, are there any significant advantages or disadvantages to creating forks vs. branches? I imagine forks keep the production repository cleaner, but branches are a bit easier to manage?

**Comment by okkhoy** [comment]
Forking allows you to contribute to projects for which you are not in the "team of collaborators" (e.g., various open-source software where you may not be in the core team). 
Also, within your own fork, you can mess as much as you want; make PR only when it is reasonable. That way the project is clean (?).

Within the same team - I don't think fork provides any huge advantage than keeping the project clean (e.g., pruning useless branches frequently, consciously)

> branches are a bit easier to manage

This is particularly dependent on how comfortable you are, and comes with usage and experience. Initially, it may seem that branches are easier, but with experience, even forking workflow may get very comfortable.

**Comment by NeilBaner** [comment]
I see. I guess I need to try all the different approaches before settling on one. Thanks for your advice. It was very helpful. I'll close this issue now.
