### ISSUE TITLE
iP: Level-0

### ISSUE THREAD

**Issue by woozije** [nus-cs2113-AY2021S1/forum#5]
Hi Prof, regarding Level-0 of the iP, the task states that we should commit after making changes, for this increment are we supposed to push the changes to the fork on github after committing? In addition, are we supposed to keep the DUKE logo that shows at the start?

**Comment by okkhoy** [comment]
1. Are we supposed to push after changes to the fork? -- Yes, please do (same holds for all tasks)
2. Are we supposed to keep the DUKE logo that shows at the start? -- You can change it to whatever you want (including retaining it or removing totally). Just please don't rename the repository 😅  (we had such instances last time, and it becomes hard to track your work).

**Comment by woozije** [comment]
Noted, thank you prof
