### ISSUE TITLE
Undo fast foward merge

### ISSUE THREAD

**Issue by woozije** [nus-cs2113-AY2021S1/forum#50]
Hi, I was merging branch-Level-6 to master branch but did not check the "Create a new commit even if fast forward is possible". It resulted in something like this:
![image](https://user-images.githubusercontent.com/37478363/93120936-ad69c800-f6f6-11ea-89be-e2a3dfa6ee6e.png)

Then I did a **git reset --keep branch-Level-6@{1}** but was unable to revert back to the previous state before merging as the branch-Level-6 returned to the 2nd last commit in branch-Level-6 and master stayed at my last commit of branch-Level-6. So I merged master back into branch-Level-6 which went back into the situation shown in the picture above.  I was unable to revert the merge after that.

How do I move master back to origin/master? Would it be safe to checkout origin/master and reset master branch there? Or may I know if there is any other solution to this?

**Comment by okkhoy** [comment]
If you haven't deleted the branches, you can try to reset the master branch to the commit where your origin/master is.
(to be cautious, you can create a copy of the repo). After that merge branch-level-6 with merge commit.

**Comment by woozije** [comment]
Thank you! It is working now.
