### ISSUE TITLE
FileNotFoundException in JAR file implementation

### ISSUE THREAD

**Issue by adinata15** [nus-cs2113-AY2021S1/forum#51]
When implementing the JAR file, I encounter the FileNotFoundException. When I tried on the normal java terminal everything works, with or without the duke.txt. Is this something we need to fix or is this ok? My code is as follows:
```
public static final String filepath = "./data/duke.txt";//file path from root file
private static void handlePastData() {
        File pastFile = new File(filepath); // create a File for the given file path
        String wholeDoc = readFile(pastFile);
        //when file is empty or not created
        if (wholeDoc == null) {
            return;//skip parsing data
        }
        //convert file entry to tasks
        parseFile(wholeDoc);
    }
```
This is the error:
![image](https://user-images.githubusercontent.com/48993548/93128552-3e926c00-f702-11ea-8674-08daea052c59.png)

**Comment by okkhoy** [comment]
You need to fix this.
Please check your saveData method as indicated in the stack trace.

**Comment by NeilBaner** [comment]
I, too, am facing something similar. The same path that works in IntelliJ no longer works when I create a JAR and test it using`java -jar`. I handled the exception, but the feature doesn't work as expected which is a bit of a shame.

**Comment by okkhoy** [comment]
Check if you have the directory structure needed. (i.e., a folder called `data` should be in the same folder as the JAR file)
If not, you need to create the directory if it is not there. Better to handle it in code.
Something like this:

  ```
  private static void createFile(File filePath) {
        try {
            if (filePath.exists()) {
                System.out.println("file exists");
                return;
            }
            if (!filePath.getParentFile().exists()) {
                filePath.getParentFile().mkdirs();
            }
            filePath.createNewFile();
        } catch (IOException e) {
            System.out.println("Cannot create file; reason: " + e.getMessage());
        }
    }
```

**Comment by adinata15** [comment]
It works now, thank you! Similar to the issue of @NeilBaner, all the symbols (ie: tick and smiley faces) does not work in JAR files anymore (it previously works on Java terminal). Is this acceptable or need to be fixed too?

**Comment by okkhoy** [comment]
For the symbols in the terminal, you need to set the encoding and a supporting font.
See: https://github.com/nus-cs2113-AY2021S1/forum/issues/47#issuecomment-691681659
It is OK if you don't fix that (or if you change tick and cross to `Y` and `N` within your code).

**Comment by NeilBaner** [comment]
For mine, there are some text files containing lists of application data (i.e. not user generated data) that I want to bundle with the application. I made sure that those text files are inside the jar, but the same path that works when running in IntelliJ don't work with the jar. Can I ask how we can access files within the jar? Should the path be something like ./ip.jar/... ?

**Comment by okkhoy** [comment]
@NeilBaner for that you need to package the data files as resource within the JAR. Else it won't be accessible (even though you dump them in the JAR).
Please check this for a quick tutorial: https://mkyong.com/java/java-read-a-file-from-resources-folder/

**Comment by adinata15** [comment]
Thank you, it is working now! @NeilBaner @okkhoy
