### ISSUE TITLE
Automated Text-UI Testing Issue: ACTUAL.TXT is empty

### ISSUE THREAD

**Issue by HengFuYuen** [nus-cs2113-AY2021S1/forum#52]
Hi prof and friends! I actually have an identical problem as in forum #33, however, even after following the suggestions to change my project structure, my runtest.bat still does not seem to work. This problem only started after I added the delete functionality into Duke. Any help will be greatly appreciated! Thank you!

The error message: (where ACTUAL.TXT is empty)
![image](https://user-images.githubusercontent.com/60005925/93281024-b85b5000-f7fd-11ea-8fa7-9e6d91b16655.png)

My project structure and runtest.bat javac and java command lines:
![image](https://user-images.githubusercontent.com/60005925/93281287-5f3fec00-f7fe-11ea-9afb-af2293cfe367.png)
![image](https://user-images.githubusercontent.com/60005925/93281324-7088f880-f7fe-11ea-9782-774143311731.png)
![image](https://user-images.githubusercontent.com/60005925/93281337-77b00680-f7fe-11ea-9177-dfb12dc6eed0.png)

My source files:
![image](https://user-images.githubusercontent.com/60005925/93281126-040df980-f7fe-11ea-953a-bb207c76d8fe.png)

**Comment by okkhoy** [comment]
Did you get it to work when you made a comment in #33?
After that, it started failing again? (Or is it the case that it never worked since #33)
I can take a look after the tutorials today and let you know.

**Comment by HengFuYuen** [comment]
@okkhoy It worked after I made the comments in #33 but failed when I’m trying to do level-6 the part where we have to add delete functions to duke. Thank you!

**Comment by jerichochua** [comment]
Maybe you can try the following? So instead of using `Duke`, it's `duke.Duke` instead, based on the structure inside the bin folder:
`java -Dfile.encoding=UTF-8 -classpath ..\bin duke.Duke < input.txt > ACTUAL.TXT`

**Comment by HengFuYuen** [comment]
@okkhoy @jerichochua Thank you so much! It finally works!
