### ISSUE TITLE
Do we add the data files generated to .gitignore?

### ISSUE THREAD

**Issue by iamchenjiajun** [nus-cs2113-AY2021S1/forum#54]
These data files are generated in the Level-7 increment of the iP. As these files are user generated, it might not be useful to others who want to test or run the project on their own computer. Does it make sense to include such files in .gitignore?

**Comment by okkhoy** [comment]
Yes, you can add them to `.gitignore`.

**Comment by iamchenjiajun** [comment]
@okkhoy Thanks for the clarification prof!
