### ISSUE TITLE
.out directory is missing

### ISSUE THREAD

**Issue by zsk612** [nus-cs2113-AY2021S1/forum#57]
According to the video, .Jar file should be found in .out/artifact directory. However, I could not find my .out directory, but everything else works well. How to solve this? Thank you!
![MISSING_OUT](https://user-images.githubusercontent.com/57080256/93450562-b4682480-f908-11ea-8c99-540dd0ac189a.JPG)

**Comment by okkhoy** [comment]
Please provide a screenshot of your project structure window as well.

**Comment by zsk612** [comment]
Okay. Here is the screenshot of my project structure window. Thank you!
![PROJECT_STRUCTURE](https://user-images.githubusercontent.com/57080256/93475552-56990400-f92b-11ea-88c9-0919a0ff7c6f.JPG)

**Comment by okkhoy** [comment]
Check your `Output directory` on the top. It is `C:\Users\zsk\IdeaProjects\artifacts\ip_jar` which is not in the `...\ip\*` path.
So you should search for the JAR in this folder: `C:\Users\zsk\IdeaProjects\artifacts\ip_jar`

**Comment by zsk612** [comment]
ohhh okok thank you prof!! But still, may I know why I do not have .out directory? Sorry that this question may sound stupid haha

**Comment by okkhoy** [comment]
Again look for the compiler output directory under the projects. I suspect it is pointing to some different directory.
![image](https://user-images.githubusercontent.com/1023494/93533224-0d6da200-f975-11ea-9644-319225e9aa61.png)

**Comment by zsk612** [comment]
Ok thank you prof!
