### ISSUE TITLE
For the increment A-MoreOOP, why do we use instances of classes instead of static methods?

### ISSUE THREAD

**Issue by daniellimzj** [nus-cs2113-AY2021S1/forum#59]
Hi,

I don't really understand about why the example code for the increment A-MoreOOP initialises instances of classes instead of just using static methods.

For example, it initialises a instance `ui` of class `Ui` to print things, but couldn't we achieve the functionality of printing things with static methods?

Would like to know if there's any benefits of using instances of classes instead of static methods in these cases that I'm missing.
Thank you!

**Comment by wangqinNick** [comment]
I think in terms of member functions: if a method do not invoke any non-static variables, the method should be static.

**Comment by daniellimzj** [comment]
> I think in terms of member functions: if a method do not invoke any non-static variables, the method should be static.

I also thought this way, that's why I was a bit confused why the example code used non-static methods even though I don't see how the methods for those classes could invoke non-static variables.

**Comment by okkhoy** [comment]
By themselves, static methods are not too bad. You can achieve the functionality using static methods. However, your code may end up becoming procedural in nature. Static methods make the code less testable. Hence, in general, favor instance methods over static methods.
See: 
1. https://se-education.org/learningresources/contents/testing/writing-testable-code.html#rule-4-avoid-static-methods
Within the page you have the following links: 
    1. https://testing.googleblog.com/2008/12/static-methods-are-death-to-testability.html
    1. https://testing.googleblog.com/2008/08/by-miko-hevery-so-you-decided-to.html

**Comment by daniellimzj** [comment]
Hi Prof,
Okay! Thank you for the clarifications.
