### ISSUE TITLE
Individual Project: updates in iP progress dashboard

### ISSUE THREAD

**Issue by lunzard** [nus-cs2113-AY2021S1/forum#6]
Hi Prof, are we able to see the updates in the iP progress dashboard [https://nus-cs2113-ay2021s1.github.io/dashboards/contents/ip-progress.html](url) now?
I have made my first commit to the forked project, with a summary "Update Level-0", but I didn't see any change in the dashboard. The last update is still on Mar 03 2020.

**Comment by okkhoy** [comment]
No, the updates are not reflected immediately. It is not fully automated. [Edit: it is not real-time sync]
We usually run the scripts before/on the day of your tutorials. So you may have to wait a bit for it to be populated 😄
