### ISSUE TITLE
How to insert pictures in the README.md?

### ISSUE THREAD

**Issue by wangqinNick** [nus-cs2113-AY2021S1/forum#60]
I want to insert several gif files in the README.md. I would like to upload the gif files to the GitHub  ip repo as well so that I could insert pictures with their urls. However, I am not sure where to put and how to upload those gif files. Should I put them in my resources folder? I am afraid of resulting in a too large jar file, generating through shadowJar.

**Comment by kstonekuan** [comment]
If your gif files are only for the README I think you can place them in the docs folder as that should not be compiled. You can then use relative paths in your README such as `![Alt Text](./gifs/one.gif)`

**Comment by wangqinNick** [comment]
> If your gif files are only for the README I think you can place them in the docs folder as that should not be compiled. You can then use relative paths in your README such as `![Alt Text](./gifs/one.gif)`

Thanks, I will try it out.
