### ISSUE TITLE
iP progress dashboard

### ISSUE THREAD

**Issue by HengFuYuen** [nus-cs2113-AY2021S1/forum#63]
Hi prof and friends!

Apparently my JAR file for week 6 was detected as my final JAR file (as shown below) in the iP progress dashboard. Did I perhaps do something wrong? Or could it be because I submitted it late?

![image](https://user-images.githubusercontent.com/60005925/94043483-97978980-fdff-11ea-946b-135c5182fe9e.png)

**Comment by zhixiangteoh** [comment]
![iP Admin Tasks Dashboard SS](https://user-images.githubusercontent.com/47135468/94048491-2c04ea80-fe06-11ea-91ac-fcb22d55ce4c.png)
^If you click the info icon under your student ID on the dashboard, you can see this short statement.

It seems you released your A-Jar two days ago, which falls within the period the script probably expects for the Final Jar.

**Comment by HengFuYuen** [comment]
Oh no...What should I do ? Would my final JAR submission be affected because of this ?

**Comment by zhixiangteoh** [comment]
> Oh no...What should I do ? Would my final JAR submission be affected because of this ?

I doubt it would, it should probably be fine if your final JAR submission is in by the deadline, and tagged A-Release.

**Comment by okkhoy** [comment]
Make another release by the deadline. So that will be used later for evaluation.

**Comment by HengFuYuen** [comment]
I see! Thanks @zhixiangteoh and @okkhoy !
