### ISSUE TITLE
Table formatting for User Guide

### ISSUE THREAD

**Issue by HengFuYuen** [nus-cs2113-AY2021S1/forum#65]
Hi prof and friends! I encountered a problem with creating tables using GFMD for the user guide and would like to request for help.

In my docs\README.md file on github the table seems to be presented properly.
![image](https://user-images.githubusercontent.com/60005925/94372032-2c1a2880-012d-11eb-8eb5-acbfde9325ea.png)

However, when I view the user guide at http://{your username}.github.io/{repo name}/ the table formatting is gone.
![image](https://user-images.githubusercontent.com/60005925/94372050-50760500-012d-11eb-88de-f9c72e56a246.png)

**Comment by hughjazzman** [comment]
Hi, try tips from #61.

**Comment by HengFuYuen** [comment]
Oh! Thanks so much for the tips!
