### ISSUE TITLE
Question Regarding iP increment A-MoreOOP

### ISSUE THREAD

**Issue by shreytheshreyas** [nus-cs2113-AY2021S1/forum#66]
Hi Prof,
I have a doubt regarding the A-MoreOOP increment for the iP. The classes that we are supposed to extract, is it a must that their instances have to be present in main class or is it ok if I have an instance of that paricular class in another class (other than the main class) ? Example: I have an instance of the storage class in the ArrayList Class.

**Comment by okkhoy** [comment]
There is no such restriction! Use it in the places that make sense.

**Comment by shreytheshreyas** [comment]
Alright Prof thanks for the clarification :)
