### ISSUE TITLE
[Urgent] JAR file cannot run on Mac due to DateTimeParseException

### ISSUE THREAD

**Issue by LIU-YiFeng-1** [nus-cs2113-AY2021S1/forum#67]
Hi prof and friends! I encountered a problem when testing my JAR file using MacBook. My JAR file is running perfectly fine on Windows and Linux but it failed to run on MacBook due to DateTimeParseException. 

I have attached a photo of the error message in this post.

![errorMessage on Mac](https://user-images.githubusercontent.com/60413927/94458640-ce4b1680-01e8-11eb-9691-8d6cb2030547.jpeg)

My JAR has no Text input named 'sunday' at all and I even deleted the output.txt (which is used to save my data), but it still shows the same error. Any kind soul can help? Much appreciated!

**Comment by daniellimws** [comment]
Double check if you deleted the correct file? Because it does look like the program is reading from a file.

**Comment by daniellimws** [comment]
Double check if you deleted the correct file? Because it does look like the program is reading from a file.

**Comment by LIU-YiFeng-1** [comment]
> Double check if you deleted the correct file? Because it does look like the program is reading from a file.

Thanks! I found the issue, there was a pre-existing txt.file.
