### ISSUE TITLE
Automated testing after dividing classes into packages

### ISSUE THREAD

**Issue by longngng** [nus-cs2113-AY2021S1/forum#68]
Hi,
After I divide classes into packages, the automated test doesn't seem to work anymore.
My code structure now looks like this
![image](https://user-images.githubusercontent.com/46754292/94544724-2a13af00-027e-11eb-9dee-2c3d7d7fb2fe.png)
I tried changing line 16 in runtest.sh to duke/Duke.java instead of just /Duke.java, but I still have errors
![image](https://user-images.githubusercontent.com/46754292/94544791-4283c980-027e-11eb-8847-00850b68c9b4.png)

![image](https://user-images.githubusercontent.com/46754292/94544847-5a5b4d80-027e-11eb-9e78-7c4a545e4aa3.png)

Does anyone have tips to fix this?

**Comment by iamchenjiajun** [comment]
I think you need to include all the other packages/classes for it to be compiled properly.

i.e. by adding ```../src/main/java/duke/task/*.java``` into the end of the line and for all the other classes.

**Comment by kstonekuan** [comment]
I think you can refer to #30

**Comment by longngng** [comment]
I see. Thanks guys!
