### ISSUE TITLE
How long should the UG be and what is the weight of UG for IP?

### ISSUE THREAD

**Issue by wangqinNick** [nus-cs2113-AY2021S1/forum#70]
In general, how many lines of User Guide should be enough to get full mark for User Guide part and what is the weight of UG for IP? Do I need to illustrate all functions in good detail ?

**Comment by okkhoy** [comment]
I would say explain all the features you have in your product at the level of detail that someone using your app will be benefitted from the UG. It is hard (and probably meaningless) to associate "how many lines" with the user guide. 
Weightage: https://nus-cs2113-ay2021s1.github.io/website/admin/ip-grading.html

**Comment by wangqinNick** [comment]
Thanks for the explanation!
