### ISSUE TITLE
Unable to run gradle file

### ISSUE THREAD

**Issue by Bryanbeh1998** [nus-cs2113-AY2021S1/forum#71]
I was unable to run my gradle file during tutorial.
The error i got was "Unknown host 'services.gradle.org'. You may need to adjust the proxy settings in Gradle."

I tried changing the setting to allow HTTPS but it still does not work.
I also deleted everything and cloned one more time but it still doesnt work.

For some reason i am unable to post a screenshot of the error onto the forum.

**Comment by daniellimws** [comment]
Might be issue with nus WiFi. Happened to my team also.

**Comment by Bryanbeh1998** [comment]
Nevermind. There was a problem with the NUS Wifi
