### ISSUE TITLE
[Key Exercise] Grade Helper: 

### ISSUE THREAD

**Issue by shreytheshreyas** [nus-cs2113-AY2021S1/forum#8]
Hi Prof, Just wanted to raise this issue there doesn't seem to be an assignment file for the Grade helper key exercise on repl.it.

**Comment by okkhoy** [comment]
Yes, this was removed on repl.it
The exercise is marked as a key exercise to get you some practice of using switch statements.

**Comment by shreytheshreyas** [comment]
oh ok noted, thanks prof :)
