### ISSUE TITLE
Java CI tests for building on different OS last too long

### ISSUE THREAD

**Issue by gy716** [nus-cs2113-AY2021S1/forum#83]
When I create a pull request to the upstream, it will be automatically tested for building on  ubuntu, windows and MacOs.
But I don't know why this process lasts too long like more than 1 hour. Are there any possible reasons casusing this?

**Comment by NeilBaner** [comment]
Hi, how were you able to solve this?

**Comment by gy716** [comment]
In our case, I changed the gradle.yml file that teacher provided in the workflow.  This file will let github automatically test runtest.bat/sh, which has some problems that will make our program keep running for hours. So we just delete that part of code in the file to not test it.
