### ISSUE TITLE
Static classes vs instances

### ISSUE THREAD

**Issue by NeilBaner** [nus-cs2113-AY2021S1/forum#88]
According to the lectures, and the notes on the website/textbook, something like 

```java
InputParser ip = new InputParser ();
arguments = ip.getArguments(input);
```

Is preferred over 
```java
arguments = InputParser.getArguments(input);
```

However, if we have a class for printing the messages in the UI, must that also be instantiated every time? It would have to be instantiated in almost every single class in our program which I feel would bloat it somewhat. On the other hand it would make it less easily testable.

**Comment by hughjazzman** [comment]
If we were to take https://se-education.org/addressbook-level3/DeveloperGuide.html#architecture as an example, then the navigability shows that `Ui` should be the one aware of the `Logic` and `Model` of the application instead of the other way round. I haven't implemented this, but if I were to guess, you could initialise the `Ui` in the main app class and check the other 2 components in the `while` loop.

**Comment by NeilBaner** [comment]
Sorry, I'm not 100% sure what you mean @hughjazzman . Am I right to say that, according to the link you sent, my Ui class should be the only one printing messages anyway?

**Comment by okkhoy** [comment]
@NeilBaner yes, if you make it such that the UI is the only one printing messages, you would have achieved good design :-)

**Comment by hughjazzman** [comment]
Let me see if I can try to illustrate. Suppose we have a `Command` class.

```Java
public class Duke {
    /** Instances of class objects for UI. **/
    private final Ui ui;
    private final Parser parser;

    private Duke() {
        ui = new Ui();
        parser = new Parser();
    }

    public void run() {
        boolean isExit = false;
        while (!isExit) {
            String line = ui.readLine();
            Command c = parser.parse(line);
            c.execute();
            isExit = c.isExit();
            ui.printCommand(c); // here, we could try have the Command c as input to the Ui instance
        }
    }

    /**
     * Main entry-point for the java.duke.Duke application.
     */
    public static void main(String[] args) {
        new Duke().run();
    }
}
```

Maybe the `Command` class might have an overridden `toString()` method? This leaves the `Logic` not having to deal with `Ui` as well.

**Comment by NeilBaner** [comment]
I see what you mean. How would you suggest I do this for exceptions though? java.lang.Exception, for example, includes a printStackTrace method which means the exception, not the UI class is responsible for printing error messages. For my ip I (not knowing better until much too late) used a static messages class and called it's methods everywhere I needed to print something, including in my DukeException.printErrorMessage().
